name: 🚀 Deploy website on push
on: 
  push:
    branches: [ master ]
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
      with:
        ref: deploy

    - name: Move into deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        BRANCH: deploy
        FOLDER: dist
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: f31-preview.runhosting.com
        username: 3868932_admin
        port: 21
        password: ${{ secrets.PROD_FTP }}
        server-dir: /
